### ISSUE TITLE
在编辑时点侧边栏中的link，将被导航至404页面

### ISSUE THREAD

**Issue by lianzhao** [HuijiWiki/bootstrap-mediawiki#2]
测试环境：Chrome 41 ＋ Mac OS X 10.10.3
再现方法：
1. 进入魔戒词条http://lotr.huiji.wiki/wiki/%E9%AD%94%E6%88%92
2. 进入源代码编辑模式
3. 选择左侧导航栏－》站点导航－》魔戒
- 预期结果：进入魔戒词条
- 实际结果：跳转至http://home.huiji.wiki/wiki/MediaWiki:404

**Comment by Reasno** [comment]
这个应该是站点本地控制的，以后会有教程推出。
