### ISSUE TITLE
编辑器的工具栏应该置顶

### ISSUE THREAD

**Issue by lianzhao** [HuijiWiki/bootstrap-mediawiki#3]
测试环境：Chrome 41+Mac OS X 10.10.3
再现方法：
1. 打开一个内容比较多的page，例如http://lotr.huiji.wiki/wiki/BugReport
2. 进入可视化编辑模式
3. 拖动浏览器的滚动条，尝试编辑page比较靠下的部分
- 预期结果：工具栏仍在顶部，可以使用
- 实际结果：工具栏已经被滚动出屏幕之外

**Comment by Reasno** [comment]
可视化编辑器bug较多，谢谢反馈

**Comment by Reasno** [comment]
Fixed!
