### ISSUE TITLE
通过uri query方式访问页面时导航栏的选中项不正确

### ISSUE THREAD

**Issue by lianzhao** [HuijiWiki/bootstrap-mediawiki#5]
测试环境：Chrome 41+Mac OS X 10.10.3
再现方法：
1. 进入某条目，例如http://lotr.huiji.wiki/index.php?title=BugReport
- 预期结果：导航栏应选中“页面”标签
- 实际结果：导航栏没有任何标签被选中

**Comment by Reasno** [comment]
暂时没想到怎么fix

**Comment by Reasno** [comment]
已fix，稍后上线。 （测试服已修正）
